### ISSUE TITLE
Collection won't install from git repo

### ISSUE THREAD

**Issue by kbreit-insight** [redhat-cop/ah_configuration#365]
# Summary

I have a requirements.yml file which installs this collection from the repo and it's failing. I am unsure if it's a problem with the collection or ansible-galaxy/requirements.yml.

# Issue Type

- Bug Report

# Ansible, Collection, Private Automation Hub details

```console (paste below)
+ ansible-galaxy --version
ansible-galaxy [core 2.15.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-galaxy
  python version = 3.9.18 (main, Sep  7 2023, 00:00:00) [GCC 11.4.1 20230605 (Red Hat 11.4.1-2)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True

```

- ansible installation method: one of source, pip, OS package, EE

# OS / ENVIRONMENT

Ubuntu

# Desired Behavior

It should build with the collection.

# Actual Behavior
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ansible/galaxy/collection/concrete_artifact_manager.py", line 301, in get_direct_collection_meta
    return self._artifact_meta_cache[collection.src]
KeyError: None
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ansible/cli/__init__.py", line 659, in cli_executor
    exit_code = cli.run()
  File "/usr/lib/python3.9/site-packages/ansible/cli/galaxy.py", line 719, in run
    return context.CLIARGS['func']()
  File "/usr/lib/python3.9/site-packages/ansible/cli/galaxy.py", line 119, in method_wrapper
    return wrapped_method(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/ansible/cli/galaxy.py", line 1338, in execute_install
    requirements = self._parse_requirements_file(
  File "/usr/lib/python3.9/site-packages/ansible/cli/galaxy.py", line 818, in _parse_requirements_file
    requirements['collections'] = [
  File "/usr/lib/python3.9/site-packages/ansible/cli/galaxy.py", line 819, in <listcomp>
    Requirement.from_requirement_dict(
  File "/usr/lib/python3.9/site-packages/ansible/galaxy/dependency_resolution/dataclasses.py", line 446, in from_requirement_dict
    req_version = art_mgr.get_direct_collection_version(tmp_inst_req)
  File "/usr/lib/python3.9/site-packages/ansible/galaxy/collection/concrete_artifact_manager.py", line 287, in get_direct_collection_version
    return self.get_direct_collection_meta(collection)['version']  # type: ignore[return-value]
  File "/usr/lib/python3.9/site-packages/ansible/galaxy/collection/concrete_artifact_manager.py", line 303, in get_direct_collection_meta
    b_artifact_path = self.get_artifact_path(collection)
  File "/usr/lib/python3.9/site-packages/ansible/galaxy/collection/concrete_artifact_manager.py", line 237, in get_artifact_path
    b_artifact_path = _extract_collection_from_git(
  File "/usr/lib/python3.9/site-packages/ansible/galaxy/collection/concrete_artifact_manager.py", line 413, in _extract_collection_from_git
    name, version, git_url, fragment = parse_scm(repo_url, coll_ver)
  File "/usr/lib/python3.9/site-packages/ansible/galaxy/collection/concrete_artifact_manager.py", line 387, in parse_scm
    if ',' in collection:
TypeError: argument of type 'NoneType' is not iterable
Error: building at STEP "RUN ansible-galaxy role install $ANSIBLE_GALAXY_CLI_ROLE_OPTS -r requirements.yml --roles-path "/usr/share/ansible/roles" -vvv": while running runtime: exit status 250
Please give some details of what is actually happening.
```

# STEPS TO REPRODUCE

```yaml (playbook/task)
collections:
  - src: git+https://github.com/ansible/galaxy_collection.git
    type: git
```

**Comment by s-hertel** [comment]
The traceback is a bug in ansible-core (it should give an informative error), but it's also an invalid requirements file for collections. Role requirements have `src` field, but collections do not (not to be confused with the collections `source` field which is a Galaxy server and unused for anything other than `type: galaxy`). This is the collection format:

```yaml
collections:
  - name: https://github.com/ansible/galaxy_collection.git
    type: git
```

The valid role requirement fields are listed [here](https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#installing-multiple-roles-from-a-file), and valid collection requirement fields are [here](https://docs.ansible.com/ansible/latest/collections_guide/collections_installing.html#install-multiple-collections-with-a-requirements-file).

**Comment by kbreit-insight** [comment]
That solved that problem but opened another. The bindep file in this repository is requesting the `python` package but in the AAP execution environments there is no package named `python` as it's normally versioned, such as `python38`. Is there a way to update the bindep file to be more restrictive about when to install `python`?

**Comment by sean-m-sullivan** [comment]
Trying to figure this out as its different for the rhel9 ee's and the rhel8 ee's which is frustrating.

**Comment by djdanielsson** [comment]
I don't understand the requirement of python38 anyways because ansible requires that already.... can we not just remove the bindep file all together?

**Comment by djdanielsson** [comment]
is this working now and can be closed?

**Comment by kbreit-insight** [comment]
I didn't see this was fixed but I will give it a try over the next few days.

**Comment by kbreit-insight** [comment]
It did work. Thank you. Closing.
